### PR TITLE
Add update checker functionality

### PR DESCRIPTION
**Pull request by royshil**
#534 

image

### CODE REVIEW

**Comment by umireon** [comment]
Can we remove Qt dependency?

**Comment by royshil** [comment]
> Can we remove Qt dependency?

we still use it for a few things. i can work on removing everything and check back in here

**Comment by umireon** [comment]
I'm OK with not removing Qt dependency now. It can be removed later.

**Review by umireon — APPROVED** [review]
LGTM

**Comment by royshil** [comment]
@umireon i've removed Qt dep
please check it out

**Review by umireon — APPROVED** [review]
LGTM

**Pull request merged**
