### PR TITLE
Add image similarity settings, RMBG, threading

### PR DESCRIPTION
**Pull request by royshil**
And increase RVM model resolution

### CODE REVIEW

**Review by umireon — APPROVED** [review]

**Comment by umireon** [comment]
I've restarted the failed jobs

**Comment by royshil** [comment]
> We have to change the build procedure

@umireon Ok, but do you know why? Or what needs to be changed?

**Comment by umireon** [comment]
It is related to 2to3

**Comment by umireon** [comment]
https://github.com/actions/runner-images/issues/9508

**Comment by umireon** [comment]
#557 merged

**Pull request merged**
