### PR TITLE
Adding simple mode for settings

### PR DESCRIPTION
**Pull request by royshil**
By default the plugin will not show all settings, which may be scary for most users
I added an "Advanced mode" checkbox which will reveal all settings

### CODE REVIEW

**Comment by umireon** [comment]
@royshil 

Some settings are shown in the initial state.
スクリーンショット 2023-09-22 22 06 24

All settings are shown when the advanced settings are checked.
スクリーンショット 2023-09-22 22 06 31

Things are odd when the advanced settings are unchecked. All the settings except the Focul blur factor are gone.
スクリーンショット 2023-09-22 22 06 35

Is this behaviour is expected?

**Comment by umireon** [comment]
@royshil ping

**Comment by umireon** [comment]
@royshil ping

**Comment by royshil** [comment]
@umireon  can you check on your end that it works properly now? 🙏

**Review by umireon — APPROVED** [review]
LGTM

**Pull request merged**
